# Generated by Django 4.1.1 on 2022-09-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("E_name", models.CharField(max_length=255)),
                ("E_email", models.EmailField(max_length=254)),
                ("R_score", models.IntegerField()),
                ("R_prediction", models.CharField(max_length=255)),
                (
                    "R_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume_app.resume",
                    ),
                ),
            ],
        ),
    ]
