# Generated by Django 4.1.1 on 2022-09-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0002_resumeanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumeanalysis",
            name="R_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resume_app.resume"
            ),
        ),
    ]
